language: dart

dart:
  - 2.0.0
  - dev

dart_task:
  - test
  - dartanalyzer: --fatal-infos --fatal-warnings .

# Only run one instance of the formatter and the analyzer, rather than running
# them against each Dart version.
matrix:
  include:
  - dart: dev
    dart_task: dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
