name: test_process
version: 1.0.0
description: A library for testing subprocesses.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/test_process

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  async: "^1.12.0"
  meta: ">=0.9.0 <2.0.0"
  path: "^1.0.0"
  test: "^0.12.19"

dev_dependencies:
  test_descriptor: "^1.0.0"
