name: test_process
version: 1.0.4

description: A package for testing subprocesses.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/test_process

environment:
  sdk: '>=2.0.0-dev.55.0 <3.0.0'

dependencies:
  async: ^2.0.7
  meta: ^1.1.5
  path: ^1.6.1
  test: ^1.2.0

dev_dependencies:
  test_descriptor: ^1.1.1
